### ISSUE TITLE
Replace this URLs with placeholders

### ISSUE THREAD

**Issue by Pethical** [i-Cell-Mobilsoft-Open-Source/DookuG-backend#65]
[These URLs](https://github.com/i-Cell-Mobilsoft-Open-Source/DookuG-backend/blob/bfef0e7adbe4bcaf8d94e6537937ae9fde676670/etc/docker-compose/.env#L1-L2) are not helpful to the user and it's not clear that they need to be replaced. Let's remove these URLs and insert appropriate placeholders in their place.
Thank you

**Comment by cserhatit** [comment]
fixed in #75
