### ISSUE TITLE
Let's remove the inappropriate URLs from the install.adoc file

### ISSUE THREAD

**Issue by Pethical** [i-Cell-Mobilsoft-Open-Source/DookuG-backend#66]
[These URLs](https://github.com/i-Cell-Mobilsoft-Open-Source/DookuG-backend/blob/bfef0e7adbe4bcaf8d94e6537937ae9fde676670/docs/install.adoc?plain=1#L96) are not useful for the Open Source user/developer. Let's remove these URLs.

**Comment by speter555** [comment]
Have to change: https://i-cell-mobilsoft-open-source.github.io/docker-wildfly/#wildfly-oracle-jdbc

**Comment by cserhatit** [comment]
fixed in #75
